# This is a sample Python script.
# @section author_main Author(s)
# - Created by mohamed hatem /sara said / mohamed maged /emad hamdy /salma swillam /kirollos nashaat/abdelrahman gamal/hasan said / on 15/11/2023.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1400, 1000)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("background-image: url(./image6.jpg)\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = AnalogueGauageWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(710, 120, 321, 291))
        self.widget.setObjectName("widget")
        self.spped_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.spped_lcd.setGeometry(QtCore.QRect(890, 420, 100, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spped_lcd.setFont(font)
        self.spped_lcd.setStyleSheet("\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-top-color: rgb(0, 0, 0);\n"
"border-color: rgb(0,85,85);\n"
"color: white;")
        self.spped_lcd.setObjectName("spped_lcd")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(440, 420, 100, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("\n"
"background-color: rgb(0, 85,85);")
        self.label_3.setObjectName("label_3")
        self.distance_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.distance_lcd.setGeometry(QtCore.QRect(540, 420, 100, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.distance_lcd.setFont(font)
        self.distance_lcd.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"border-top-color: rgb(0, 0, 0);\n"
"border-color: rgb(0,85,85);\n"
"color: white;")
        self.distance_lcd.setObjectName("distance_lcd")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(549, 20, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background: rgb(0,85,85);\n"
"font: 18pt \"Archivo\";\n"
"border-radius: 15px;\n"
"color: white;")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(790, 420, 100, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("\n"
"background-color: rgb(0, 85, 85);")
        self.label_5.setObjectName("label_5")
        self.widget_2 = AnalogueGauageWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(370, 120, 321, 291))
        self.widget_2.setObjectName("widget_2")
        self.rainicon1 = QtWidgets.QLabel(self.centralwidget)
        self.rainicon1.setGeometry(QtCore.QRect(170, 350, 151, 71))
        self.rainicon1.setText("")
        self.rainicon1.setPixmap(QtGui.QPixmap("./images/rain alarm.png"))
        self.rainicon1.setScaledContents(True)
        self.rainicon1.setObjectName("rainicon1")
        self.left_blind_spot = QtWidgets.QLabel(self.centralwidget)
        self.left_blind_spot.setGeometry(QtCore.QRect(170, 160, 151, 71))
        self.left_blind_spot.setText("")
        self.left_blind_spot.setPixmap(QtGui.QPixmap("./images/left blind.png"))
        self.left_blind_spot.setScaledContents(True)
        self.left_blind_spot.setObjectName("left_blind_spot")
        self.ACC = QtWidgets.QLabel(self.centralwidget)
        self.ACC.setGeometry(QtCore.QRect(660, 120, 81, 61))
        self.ACC.setText("")
        self.ACC.setPixmap(QtGui.QPixmap("./images/ACC.png"))
        self.ACC.setScaledContents(True)
        self.ACC.setObjectName("ACC")
        self.right_lane = QtWidgets.QLabel(self.centralwidget)
        self.right_lane.setGeometry(QtCore.QRect(1080, 260, 151, 71))
        self.right_lane.setText("")
        self.right_lane.setPixmap(QtGui.QPixmap("./images/right lane.png"))
        self.right_lane.setScaledContents(True)
        self.right_lane.setObjectName("right_lane")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(170, 50, 231, 91))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("./images/car2.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 50, 161, 131))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("./images/map.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1260, 180, 91, 201))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("./images/car condition.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.left_warning = QtWidgets.QLabel(self.centralwidget)
        self.left_warning.setGeometry(QtCore.QRect(240, 70, 51, 51))
        self.left_warning.setText("")
        self.left_warning.setPixmap(QtGui.QPixmap("./images/alarm.jpg"))
        self.left_warning.setScaledContents(True)
        self.left_warning.setObjectName("left_warning")
        self.rightwarning = QtWidgets.QLabel(self.centralwidget)
        self.rightwarning.setGeometry(QtCore.QRect(1110, 70, 51, 51))
        self.rightwarning.setText("")
        self.rightwarning.setPixmap(QtGui.QPixmap("./images/alarm.jpg"))
        self.rightwarning.setScaledContents(True)
        self.rightwarning.setObjectName("rightwarning")
        self.right_blind_spot = QtWidgets.QLabel(self.centralwidget)
        self.right_blind_spot.setGeometry(QtCore.QRect(1080, 160, 151, 71))
        self.right_blind_spot.setText("")
        self.right_blind_spot.setPixmap(QtGui.QPixmap("./images/right blind.png"))
        self.right_blind_spot.setScaledContents(True)
        self.right_blind_spot.setObjectName("right_blind_spot")
        self.left_lane = QtWidgets.QLabel(self.centralwidget)
        self.left_lane.setGeometry(QtCore.QRect(170, 260, 151, 71))
        self.left_lane.setText("")
        self.left_lane.setPixmap(QtGui.QPixmap("./images/left lane.png"))
        self.left_lane.setScaledContents(True)
        self.left_lane.setObjectName("left_lane")
        self.rain_icon2 = QtWidgets.QLabel(self.centralwidget)
        self.rain_icon2.setGeometry(QtCore.QRect(1080, 350, 151, 71))
        self.rain_icon2.setText("")
        self.rain_icon2.setPixmap(QtGui.QPixmap("./images/rain alarm.png"))
        self.rain_icon2.setScaledContents(True)
        self.rain_icon2.setObjectName("rain_icon2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 220, 47, 281))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./images/speed.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(1000, 50, 231, 91))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("./images/car1.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        
        self.widget.raise_()
        self.spped_lcd.raise_()
        self.distance_lcd.raise_()
        self.lineEdit.raise_()
        self.label_5.raise_()
        self.widget_2.raise_()
        self.rainicon1.raise_()
        self.left_blind_spot.raise_()
        self.ACC.raise_()
        self.right_lane.raise_()
        self.label_3.raise_()
        self.label_17.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.left_warning.raise_()
        self.right_blind_spot.raise_()
        self.left_lane.raise_()
        self.rain_icon2.raise_()
        self.label.raise_()
        self.label_20.raise_()
        self.rightwarning.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">distance</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">speed</span></p></body></html>"))
from AnalogueGauageWidget import AnalogueGauageWidget
